### ISSUE TITLE
optimum_allocation.R, allocation rounding

### ISSUE THREAD

**Issue by JessMK** [yangjasp/optimall#4]
Good morning. I am having an issue with my optimum_allocation output, Neyman method, where the optimum sample number to allocate to each stratum is not totaling to the nsample specified. I have included the code and output to highlight the issue. I am specifically looking at the middle option, where nsample = 140. You can see the stratum_size is outputting identical to the one prior, requesting nsample = 139. Can you please help me understand the discrepancy. If it helps, when we ran it in SAS, it provided the same statrum_size for 5B/C/D, and for strata 5E it gave 31. Thank you for your help.   
[Neyman Allocation Output.pdf](https://github.com/user-attachments/files/16932290/Neyman.Allocation.Output.pdf)

**Comment by yangjasp** [comment]
Hi Jess,

Thanks for reaching out and including the code and output. 

I believe that the discrepancy here is due to different approaches to rounding. Neyman's allocation method is to allocate samples to strata proportional to the product of the stratum size and standard deviation, which does not usually lead to integer-valued sample sizes. So, providing integer-valued stratum sizes requires adoption of some rounding strategy.  The current version of Optimall uses a simple rounding strategy - it simply rounds to the nearest integer. This does not guarantee that the stratum sample sizes add up to the desired total sample size after rounding. I cannot speak for certain on the way that SAS is doing it, but I assume it uses a different rounding strategy such as [controlled rounding](https://doi.org/10.2307/2289455) which does guarantee that the stratum sample sizes add up to the desired total sample size.

The reason that Optimall does not (currently) use controlled rounding is because the `optimum_allocation()` function allows for (in fact, it defaults to) use of the Wright algorithm, which is an alternative method to Neyman that a) guarantees that stratum sample sizes add up to the desired total and b) gives the exactly optimal integer-valued allocation. Note that controlled rounding does not always provide b)! 

In fact, the example you provided demonstrates the difference between Wright's exact algorithm and the apparently sub-optimal rounding that SAS uses by default:

```
> library(optimall)
> data <- data.frame(
+   strata = c("5B", "5C", "5D", "5E"),
+   size = c(129, 35, 120, 81),
+   sd = c(10.10, 12.79, 12.38, 11.06))

> optimum_allocation(
+   data = data, strata = "strata",
+   sd_h = "sd", N_h = "size",
+   nsample = 140, method = "Neyman") # Matching what you are seeing

  strata N_h  sd_h    n_sd stratum_fraction    sd npop stratum_size
1     5B 129 10.10 1302.90             0.32 10.10  129           44
2     5C  35 12.79  447.65             0.11 12.79   35           15
3     5D 120 12.38 1485.60             0.36 12.38  120           50
4     5E  81 11.06  895.86             0.22 11.06   81           30

> optimum_allocation(
+   data = data, strata = "strata",
+   sd_h = "sd", N_h = "size",
+   nsample = 140, method = "WrightII") # This is the exactly optimal allocation

  strata npop    sd    n_sd stratum_fraction stratum_size
1     5B  129 10.10 1302.90             0.31           44
2     5C   35 12.79  447.65             0.11           15
3     5D  120 12.38 1485.60             0.36           51
4     5E   81 11.06  895.86             0.21           30
```

Although SAS gave 31 samples to 5E, Wright's algorithm indicates that the exactly optimal allocation gives 30 to 5E and 51 to 5D. 

Of course, these are tiny discrepancies which aren't likely to make much of a difference in the long run, but I hope this clears things up. For further reading about this, see [here](https://www.census.gov/content/dam/Census/library/working-papers/2014/adrm/rrs2014-07.pdf).

Best,
Jasper
